# Site settings
title: Gonzalo Iglesias Vilachán

# Build settings
markdown: kramdown
highlighter: pygments

# Gems
gems:
  - jekyll-assets
  - jekyll-multiple-languages-plugin

# Localization
languages: ["es", "en"]
language_default: 'es'
exclude_from_localizations: ["javascript", "images", "css"]
