# Site settings
title: "gonzaloiv.es"

# Build settings
markdown: kramdown
highlighter: pygments

# Gems
gems:
  - jekyll-assets
  - jekyll-multiple-languages-plugin

# Localization
languages: ["es"]
language_default: "es"
exclude_from_localizations: ["javascript", "images", "css"]