# Site settings
title: gonzaloiv
author: Gonzalo Iglesias Vilachán
email: gonzalo_iglesias_vilachan@hotmail.com
description: "Media, Culture and Code"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.elpanoptico.xyz" # the base hostname & protocol for your site
twitter_username: iamgonzaloiv
github_username:  gonzaloiv

# Theme settings
include_content: true
logo: "/assets/img/logo.png"

# Build settings
include: ['_pages']
markdown: kramdown
highlighter: pygments

