# Site settings
title: gonzaloiv
author: Gonzalo Iglesias Vilachán
description: Media, Culture and Code
email: gonzalo_iglesias_vilachan@hotmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.elpanoptico.xyz" # the base hostname & protocol for your site
twitter_username: iamgonzaloiv
github_username:  gonzaloiv

# Build settings
markdown: kramdown
highlighter: pygments

# Gems
gems:
  - jekyll-assets
  - jekyll-multiple-languages-plugin

# Localization
languages: ["es", "en"]
language_default: 'es'
exclude_from_localizations: ["javascript", "images", "css"]
