# Site settings
title: "gonzaloiv.es"
baseurl: ""

# Build settings
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge

# Gems
gems:
  - jekyll-assets
  - jekyll-multiple-languages-plugin

# Localization
languages: ["es", "en"]
language_default: "en"
exclude_from_localizations: ["javascript", "images", "css"]